MAX_NUM_VEHICLES = 4

MAX_NUM_REQUEST = 20
VEH_CAPACITY = 5
MAX_WAIT_TIME = 10
MAX_INVEHICLE_TIME = 10

VEHICLE_INPUT_DIM = 53
REQUEST_INPUT_DIM = 55
RELATION_INPUT_DIM = 2

POSSIBLE_ACTION = MAX_NUM_REQUEST + 1

config_list = [
    {
        "hidden_dim": 128
    },
    {
        "hidden_dim": 256
    }
]